
import Navbar from '../components/Navbar/index'
import Head from '../components/Head/index'
import Link from 'next/link'
import Script from 'next/script'
import Page2 from '../components/Page2/index'
import Page3 from '../components/Page3/index'
import Page4 from '../components/Page4/index'
import Page5 from '../components/Page5/index'
import Page6 from '../components/Page6/index'
import Footer from '../components/Footer/index'





export default function Home (){
  return (

<section className="id-main">
  <Navbar/>
  <Head/>
  <head>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="initial-scale=1.0, width=device-width" />
<link rel="icon" href="/favicon.ico" />
</head>
<Link href="https://www.worldfoodprize.org/en/dr_norman_e_borlaug/about_norman_borlaug/">
  <a></a>
</Link>
<Link href="https://bgri.cornell.edu/dr-norman-borlaug/">
  <a></a>
  </Link>
  <Page2 />
  <Page3 />
  <Page4 />
  <Page5 />
  <Page6 />
  <Footer/>

 
   
  <Script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></Script>
</section>

  );
};


